//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ash.Portfolio.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ash.Portfolio.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 AS Level.
        /// </summary>
        internal static string _1_AS_Level {
            get {
                return ResourceManager.GetString("1 AS Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 A Levels.
        /// </summary>
        internal static string _4_A_Levels {
            get {
                return ResourceManager.GetString("4 A Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 GCSEs.
        /// </summary>
        internal static string _8_GCSEs {
            get {
                return ResourceManager.GetString("8 GCSEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Factory.
        /// </summary>
        internal static string Abstract_Factory {
            get {
                return ResourceManager.GetString("Abstract Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications Engineer.
        /// </summary>
        internal static string Applications_Engineer {
            get {
                return ResourceManager.GetString("Applications Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashley Gibson.
        /// </summary>
        internal static string Ashley_Gibson {
            get {
                return ResourceManager.GetString("Ashley Gibson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASOS.
        /// </summary>
        internal static string ASOS {
            get {
                return ResourceManager.GetString("ASOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed, developed, tested and maintained in-house C# .NET Core Web Applications using Azure Cloud Computing.
        /// </summary>
        internal static string ASOS_Senior_Software_Engineer_Bullet_1 {
            get {
                return ResourceManager.GetString("ASOS Senior Software Engineer Bullet 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used WebAPI for developing secure internal API endpoints.
        /// </summary>
        internal static string ASOS_Senior_Software_Engineer_Bullet_2 {
            get {
                return ResourceManager.GetString("ASOS Senior Software Engineer Bullet 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Tested using Moq and Dapper for Microservices and Database mocking.
        /// </summary>
        internal static string ASOS_Senior_Software_Engineer_Bullet_3 {
            get {
                return ResourceManager.GetString("ASOS Senior Software Engineer Bullet 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created and managed SQL Databases using Stored Procedures and testing using T-SQL.
        /// </summary>
        internal static string ASOS_Senior_Software_Engineer_Bullet_4 {
            get {
                return ResourceManager.GetString("ASOS Senior Software Engineer Bullet 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps for CI/CD Pipelines, Source Control and Project Management.
        /// </summary>
        internal static string ASOS_Senior_Software_Engineer_Bullet_5 {
            get {
                return ResourceManager.GetString("ASOS Senior Software Engineer Bullet 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed using TDD and SOLID principles as a standard.
        /// </summary>
        internal static string ASOS_Senior_Software_Engineer_Bullet_6 {
            get {
                return ResourceManager.GetString("ASOS Senior Software Engineer Bullet 6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSc (Hons) Computer Science for Games.
        /// </summary>
        internal static string BSc__Hons__Computer_Science_for_Games {
            get {
                return ResourceManager.GetString("BSc (Hons) Computer Science for Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of Responsibility.
        /// </summary>
        internal static string Chain_of_Responsibility {
            get {
                return ResourceManager.GetString("Chain of Responsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Courses.
        /// </summary>
        internal static string Coding_Courses {
            get {
                return ResourceManager.GetString("Coding Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Developer.
        /// </summary>
        internal static string Digital_Developer {
            get {
                return ResourceManager.GetString("Digital Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download My CV.
        /// </summary>
        internal static string Download_My_CV {
            get {
                return ResourceManager.GetString("Download My CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallagher.
        /// </summary>
        internal static string Gallagher {
            get {
                return ResourceManager.GetString("Gallagher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed, developed, tested and maintained C# .NET MVC CMS Websites and Web Applications (HTML/JavaScript/CSS) predominantly using Sitecore.
        /// </summary>
        internal static string Gallagher_Digital_Developer_Bullet_1 {
            get {
                return ResourceManager.GetString("Gallagher Digital Developer Bullet 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Control: Bitbucket, Azure DevOps and TFS.
        /// </summary>
        internal static string Gallagher_Digital_Developer_Bullet_2 {
            get {
                return ResourceManager.GetString("Gallagher Digital Developer Bullet 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenkins and WebDeploy for Continuous Integration and deployment.
        /// </summary>
        internal static string Gallagher_Digital_Developer_Bullet_3 {
            get {
                return ResourceManager.GetString("Gallagher Digital Developer Bullet 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server Management Studio for database management.
        /// </summary>
        internal static string Gallagher_Digital_Developer_Bullet_4 {
            get {
                return ResourceManager.GetString("Gallagher Digital Developer Bullet 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adhered to Government standard security measures for IT Systems including frequent and extensive security training.
        /// </summary>
        internal static string Gallagher_Digital_Developer_Bullet_5 {
            get {
                return ResourceManager.GetString("Gallagher Digital Developer Bullet 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s what I&apos;ve learnt....
        /// </summary>
        internal static string Here_s_what_I_ve_learnt___ {
            get {
                return ResourceManager.GetString("Here\'s what I\'ve learnt...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey I&apos;m.
        /// </summary>
        internal static string Hey_I_m {
            get {
                return ResourceManager.GetString("Hey I\'m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons made by.
        /// </summary>
        internal static string Icons_made_by {
            get {
                return ResourceManager.GetString("Icons made by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string In_Progress {
            get {
                return ResourceManager.GetString("In Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        internal static string Interests {
            get {
                return ResourceManager.GetString("Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed, developed, tested and maintained advanced systems for data analysis, control, automation and networking using the ThingWorx IDE.
        /// </summary>
        internal static string InVMA_Applications_Engineer_Bullet_1 {
            get {
                return ResourceManager.GetString("InVMA Applications Engineer Bullet 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked as an integral part of a team, and independently, to produce systems for global clients such as Doosan Babcock, Rotork and Atlas Copco.
        /// </summary>
        internal static string InVMA_Applications_Engineer_Bullet_2 {
            get {
                return ResourceManager.GetString("InVMA Applications Engineer Bullet 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended and hosted meetings with clients and colleagues to create satisfactory products for all end users.
        /// </summary>
        internal static string InVMA_Applications_Engineer_Bullet_3 {
            get {
                return ResourceManager.GetString("InVMA Applications Engineer Bullet 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci-Style Agile Development.
        /// </summary>
        internal static string InVMA_Applications_Engineer_Bullet_4 {
            get {
                return ResourceManager.GetString("InVMA Applications Engineer Bullet 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InVMA Ltd (Konektio AssetMinder).
        /// </summary>
        internal static string InVMA_Ltd__Konektio_AssetMinder_ {
            get {
                return ResourceManager.GetString("InVMA Ltd (Konektio AssetMinder)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is licensed by.
        /// </summary>
        internal static string is_licensed_by {
            get {
                return ResourceManager.GetString("is licensed by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump! - C# Unity.
        /// </summary>
        internal static string Jump____C__Unity {
            get {
                return ResourceManager.GetString("Jump! - C# Unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Developer.
        /// </summary>
        internal static string Junior_Developer {
            get {
                return ResourceManager.GetString("Junior Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miller Solutions Ltd.
        /// </summary>
        internal static string Miller_Solutions_Ltd {
            get {
                return ResourceManager.GetString("Miller Solutions Ltd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed, developed, tested and maintained C# ASP.NET Core Web Applications, WordPress websites and NOPCommerce websites.
        /// </summary>
        internal static string Miller_Solutions_Software_Developer_Bullet_1 {
            get {
                return ResourceManager.GetString("Miller Solutions Software Developer Bullet 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server Database management, Searchlight server maintenance, Dynamics 365 CRM ticketing and IT Glue documentation management.
        /// </summary>
        internal static string Miller_Solutions_Software_Developer_Bullet_2 {
            get {
                return ResourceManager.GetString("Miller Solutions Software Developer Bullet 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produced Release Notes, Bug Logs and other documentation records for both End Users and internal developers.
        /// </summary>
        internal static string Miller_Solutions_Software_Developer_Bullet_3 {
            get {
                return ResourceManager.GetString("Miller Solutions Software Developer Bullet 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My career so far....
        /// </summary>
        internal static string My_career_so_far___ {
            get {
                return ResourceManager.GetString("My career so far...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My experiences in pictures....
        /// </summary>
        internal static string My_experiences_in_pictures___ {
            get {
                return ResourceManager.GetString("My experiences in pictures...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My projects so far....
        /// </summary>
        internal static string My_projects_so_far___ {
            get {
                return ResourceManager.GetString("My projects so far...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherthorpe School.
        /// </summary>
        internal static string Netherthorpe_School {
            get {
                return ResourceManager.GetString("Netherthorpe School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherthorpe School &amp; Sixth Form.
        /// </summary>
        internal static string Netherthorpe_School___Sixth_Form {
            get {
                return ResourceManager.GetString("Netherthorpe School & Sixth Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Manipulator.
        /// </summary>
        internal static string Number_Manipulator {
            get {
                return ResourceManager.GetString("Number Manipulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or click the project links below.
        /// </summary>
        internal static string or_click_the_project_links_below {
            get {
                return ResourceManager.GetString("or click the project links below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or view my.
        /// </summary>
        internal static string or_view_my {
            get {
                return ResourceManager.GetString("or view my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Finder.
        /// </summary>
        internal static string Path_Finder {
            get {
                return ResourceManager.GetString("Path Finder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit my.
        /// </summary>
        internal static string Please_visit_my {
            get {
                return ResourceManager.GetString("Please visit my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluralSight.
        /// </summary>
        internal static string PluralSight {
            get {
                return ResourceManager.GetString("PluralSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics studied: C#, .NET, Security, Docker, Kubernetes, Jenkins and Sitecore.
        /// </summary>
        internal static string PluralSight_Bullet_1 {
            get {
                return ResourceManager.GetString("PluralSight Bullet 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses completed: 15.
        /// </summary>
        internal static string PluralSight_Bullet_2 {
            get {
                return ResourceManager.GetString("PluralSight Bullet 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours watched: 43.55.
        /// </summary>
        internal static string PluralSight_Bullet_3 {
            get {
                return ResourceManager.GetString("PluralSight Bullet 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My PluralSight link:.
        /// </summary>
        internal static string PluralSight_Bullet_4 {
            get {
                return ResourceManager.GetString("PluralSight Bullet 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        internal static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed, developed, tested and maintained C# .NET CMS Websites and Web Applications.
        /// </summary>
        internal static string QUBA_Junior_Developer_Bullet_1 {
            get {
                return ResourceManager.GetString("QUBA Junior Developer Bullet 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Platforms: Kentico, Sitefinity, SiteCore, Umbraco.
        /// </summary>
        internal static string QUBA_Junior_Developer_Bullet_2 {
            get {
                return ResourceManager.GetString("QUBA Junior Developer Bullet 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint, Jira and Confluence for documentation and development tracking.
        /// </summary>
        internal static string QUBA_Junior_Developer_Bullet_3 {
            get {
                return ResourceManager.GetString("QUBA Junior Developer Bullet 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Control: Bitbucket - TortoiseSVN and Sourcetree.
        /// </summary>
        internal static string QUBA_Junior_Developer_Bullet_4 {
            get {
                return ResourceManager.GetString("QUBA Junior Developer Bullet 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server Management Studio for database management.
        /// </summary>
        internal static string QUBA_Junior_Developer_Bullet_5 {
            get {
                return ResourceManager.GetString("QUBA Junior Developer Bullet 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUBA New Media Ltd.
        /// </summary>
        internal static string QUBA_New_Media_Ltd {
            get {
                return ResourceManager.GetString("QUBA New Media Ltd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching Algorithms.
        /// </summary>
        internal static string Searching_Algorithms {
            get {
                return ResourceManager.GetString("Searching Algorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Prefect, Form Representative and Sports Leader.
        /// </summary>
        internal static string Senior_Prefect__Form_Representative_and_Sports_Leader {
            get {
                return ResourceManager.GetString("Senior Prefect, Form Representative and Sports Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Software Engineer.
        /// </summary>
        internal static string Senior_Software_Engineer {
            get {
                return ResourceManager.GetString("Senior Software Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows - C++ DirectX 11.
        /// </summary>
        internal static string Shadows___C___DirectX_11 {
            get {
                return ResourceManager.GetString("Shadows - C++ DirectX 11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheffield Hallam University.
        /// </summary>
        internal static string Sheffield_Hallam_University {
            get {
                return ResourceManager.GetString("Sheffield Hallam University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming languages: C++, C#, C for Robotics, VB, JavaScript, HTML, CSS, PHP, SQL, Python and Assembly.
        /// </summary>
        internal static string Sheffield_Hallam_University_Bullet_1 {
            get {
                return ResourceManager.GetString("Sheffield Hallam University Bullet 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software used: Visual Studio, Unity.
        /// </summary>
        internal static string Sheffield_Hallam_University_Bullet_2 {
            get {
                return ResourceManager.GetString("Sheffield Hallam University Bullet 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Control: Bitbucket with Source Tree.
        /// </summary>
        internal static string Sheffield_Hallam_University_Bullet_3 {
            get {
                return ResourceManager.GetString("Sheffield Hallam University Bullet 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a look at the Games area of my.
        /// </summary>
        internal static string Sheffield_Hallam_University_Bullet_4 {
            get {
                return ResourceManager.GetString("Sheffield Hallam University Bullet 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media icons created by.
        /// </summary>
        internal static string Social_Media_icons_created_by {
            get {
                return ResourceManager.GetString("Social Media icons created by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Developer.
        /// </summary>
        internal static string Software_Developer {
            get {
                return ResourceManager.GetString("Software Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLID Principles.
        /// </summary>
        internal static string SOLID_Principles {
            get {
                return ResourceManager.GetString("SOLID Principles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot and the Zombies.
        /// </summary>
        internal static string Spot_and_the_Zombies {
            get {
                return ResourceManager.GetString("Spot and the Zombies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable Matching.
        /// </summary>
        internal static string Stable_Matching {
            get {
                return ResourceManager.GetString("Stable Matching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Market Dashboard.
        /// </summary>
        internal static string Stock_Market_Dashboard {
            get {
                return ResourceManager.GetString("Stock Market Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic Tac Toe.
        /// </summary>
        internal static string Tic_Tac_Toe {
            get {
                return ResourceManager.GetString("Tic Tac Toe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warriors Walk - C# Unity (Mobile Game with .apk).
        /// </summary>
        internal static string Warriors_Walk___C__Unity__Mobile_Game_with__apk_ {
            get {
                return ResourceManager.GetString("Warriors Walk - C# Unity (Mobile Game with .apk)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Quiz.
        /// </summary>
        internal static string Web_Quiz {
            get {
                return ResourceManager.GetString("Web Quiz", resourceCulture);
            }
        }
    }
}
